import dotenv from "dotenv";
dotenv.config();
import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

// Reasoning Agent for Oracle 10g (NO IDENTITY syntax)
export async function reasoningAgent(userPrompt) {
  try {
    console.log("🧠 Processing user prompt with Gemini...");

    const model = genAI.getGenerativeModel({ model: "models/gemini-2.5-flash" });

    const prompt = `
You are an expert Oracle SQL assistant for **Oracle Database 10g**.

The user gives you a natural language command.
You must return ONLY pure SQL (no markdown, no explanations).

⚙️ Strict Rules:
- Oracle 10g does NOT support "GENERATED AS IDENTITY". NEVER use it.
- For auto-increment primary keys:
  1. Create the table with NUMBER type.
- Always end statements with semicolons.
- No markdown, no \`\`\`sql fences, only raw SQL.
- Ensure valid Oracle 10g syntax (VARCHAR2, DATE, NUMBER, etc.).

Example:
User: create a table students with id, name, and age  
Output:
CREATE TABLE students (
  id NUMBER PRIMARY KEY,
  name VARCHAR2(100),
  age NUMBER);


Now generate for: ${userPrompt}
`;

    const result = await model.generateContent(prompt);
    const response = result.response.text().trim();

    console.log("✅ SQL generated by reasoning agent:\n", response);
    return response;
  } catch (error) {
    console.error("❌ Error generating SQL:", error);
    return null;
  }
}
