dotenv.config({ override: true });
import dotenv from "dotenv";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { retrieveSchema } from "./rag/retrieveSchema.js";
console.log("Gemini Key:", process.env.GEMINI_API_KEY.substring(0,8));
const genAI = new GoogleGenerativeAI('');

// Reasoning Agent for Oracle 10g (NO IDENTITY syntax)
export async function reasoningAgent(userPrompt) {
  try {
    console.log("Gemini Key:", process.env.GEMINI_API_KEY.substring(0,8));
    
    console.log("🧠 Processing user prompt with Gemini...");


    // ⭐ RAG STEP
    const relevantSchema = await retrieveSchema(userPrompt);


    console.log("📚 Retrieved Schema:");
    console.log(relevantSchema);



    const model = genAI.getGenerativeModel({
      model: "gemini-flash-latest"
    });


    const prompt = `
You are an expert Oracle SQL assistant for Oracle Database 10g.

The user gives you a natural language command.
Generate ONLY pure SQL.

DATABASE SCHEMA INFORMATION:

${relevantSchema.join("\n\n")}


STRICT RULES:

- Use ONLY tables and columns provided in the schema.
- Oracle Database version is 10g.
- Never use GENERATED AS IDENTITY.
- Use NUMBER, VARCHAR2, DATE datatypes.
- Always end SQL with semicolon.
- No markdown.
- No explanation.
- Return only SQL.


USER REQUEST:

${userPrompt}


Generate SQL:
`;



    const result = await model.generateContent(prompt);

    const response = result.response.text().trim();


    console.log(
      "✅ SQL generated by reasoning agent:\n",
      response
    );


    return response;


  } catch(error){

    console.error(
      "❌ Error generating SQL:",
      error
    );

    return null;
  }
}
