// server.js

import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import { reasoningAgent } from "./reasoningAgent.js";
import { databaseAgent } from "./databaseAgent.js";
import { validationAgent } from "./validationAgent.js"; // Now fully implemented
import { memoryAgent } from "./memoryAgent.js";
import { loggerAgent } from "./loggerAgent.js";
import { errorRecoveryAgent } from "./errorRecoveryAgent.js";

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

app.post("/api/query", async (req, res) => {
    try {
        // Added flag: isApproved will be true for the second request (after user clicks 'Run')
        const { query, isApproved } = req.body;
        console.log(`🧠 User Query: ${query} (Approved: ${!!isApproved})`);
        loggerAgent(`User Query: ${query} | Approved: ${!!isApproved}`);

        // 🧠 Step 1: Reasoning Agent -> Generate SQL
        const sqlQuery = await reasoningAgent(query);
        console.log("✅ SQL generated by reasoning agent:\n", sqlQuery);

        // 🧩 Step 2: Validation Agent -> Check Safety
        const validationResult = validationAgent(sqlQuery);
        const safeQuery = validationResult.sql; // Use original SQL from validation object

        // --- NEW: Step 2.5: Mandatory Approval Check (The Gate) ---
        if (!validationResult.isSafe && !isApproved) {
            console.warn(`🚨 HIGH-RISK Command (${validationResult.commandType}) detected.`);
            loggerAgent(`HIGH-RISK Query requires approval: ${safeQuery}`);
            
            // Send a special status back to the frontend to trigger the approval modal
            return res.json({
                success: false,
                requiresApproval: true,
                sql: safeQuery,
                command: validationResult.commandType,
                message: `⚠️ This is a ${validationResult.commandType} command. Please confirm execution.`
            });
        }
        // --- END APPROVAL CHECK ---

        // 💾 Step 3: Save to Memory (Only log the final query that runs)
        memoryAgent.setLastQuery(safeQuery);

        // 🗄️ Step 4: Execute via Database Agent
        try {
            // databaseAgent now handles the Audit Log insert/update internally
            const result = await databaseAgent(safeQuery, query); 

            loggerAgent(`Executed: ${safeQuery}\nResult: ${JSON.stringify(result)}`);

            return res.json({
                success: true,
                sql: safeQuery,
                result,
                message: "✅ Query executed successfully!",
                lastQuery: memoryAgent.getLastQuery(),
                // Optional message for approved queries
                approvalMessage: isApproved ? `[Approved ${validationResult.commandType} command executed.]` : null
            });
        } catch (dbError) {
            // ❌ Step 5: Database Error Handling
            console.error("❌ Database error:", dbError.message);
            loggerAgent(`Database Error: ${dbError.message}`);

            // 🩺 Step 6: Trigger Error Recovery Agent
            console.log("🩺 Invoking Error Recovery Agent...");
            const recoveredSQL = await errorRecoveryAgent(
                safeQuery,
                dbError.message,
                query
            );

            // Note: Recovery Agent needs to coordinate with databaseAgent's audit logging

            if (!recoveredSQL) {
                // databaseAgent should log final failure, here we just return the error
                return res.status(500).json({
                    success: false,
                    error: dbError.message,
                    message: "❌ Recovery failed: could not generate corrected SQL",
                });
            }

            console.log("✅ Recovered SQL:", recoveredSQL);

            // 🧱 Step 7: Try executing recovered SQL sequentially (use a new database agent call)
            const queries = recoveredSQL
                .split(";")
                .map((q) => q.trim())
                .filter((q) => q.length > 0);

            let recoveryResult = null;
            let finalSuccess = false;

            for (const q of queries) {
                try {
                    console.log("🔁 Retrying with recovered SQL:", q);
                    // NOTE: This recursive call to databaseAgent is simple but risks double logging. 
                    // A better approach (shown in databaseAgent update) is to handle recovery inside databaseAgent.
                    // For now, let's keep the logic simple here:
                    recoveryResult = await databaseAgent(q, query, { isRecovery: true, originalFailedSql: safeQuery, originalError: dbError.message });
                    finalSuccess = true;
                } catch (retryError) {
                    console.error("❌ Recovery query failed:", retryError.message);
                    loggerAgent(`Recovery query failed: ${retryError.message}`);
                    return res.status(500).json({
                        success: false,
                        error: retryError.message,
                        message: "❌ Recovery query execution failed",
                    });
                }
            }
            
            if (finalSuccess) {
                loggerAgent(`Recovery succeeded: ${JSON.stringify(recoveryResult)}`);

                return res.json({
                    success: true,
                    sql: recoveredSQL,
                    result: recoveryResult,
                    message: "✅ Query recovered and executed successfully!",
                    recoveryMessage: `Successfully recovered from error: ${dbError.message.split('\n')[0]}`
                });
            }
        }
    } catch (error) {
        console.error("❌ Server Error:", error.message);
        loggerAgent(`Server Error: ${error.message}`);
        res.status(500).json({
            success: false,
            error: error.message,
        });
    }
});

app.listen(5000, () =>
    console.log("🚀 Server running on http://localhost:5000")
);